apiVersion: apps/v1
kind: Deployment
metadata:
  name: yobot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yobot
  template:
    metadata:
      labels:
        app: yobot
    spec:
      containers:
        - name: yobot
          image: ghcr.io/aiboosts/yobot-with-trivy-output:latest
          command: ["python", "/app/main.py"]
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama-service:11434
      imagePullSecrets:
        - name: ghcr-secret
